version: "3.8"

services:
  nginx:
    build: ./nginx
    container_name: "web-server"
    restart: always
    ports:
      - 80:80
    depends_on:
      - django

  django:
    build: .
    container_name: "django-app"
    ports:
      - 8001:8001
    restart: always
    command: gunicorn resto.wsgi --bind 0.0.0.0:8001
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql
    container_name: "db-app"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=djefry
      - MYSQL_DATABASE=db_tes
    volumes:
      - ./data/mysql/db:/var/lib/mysql